In [1]:
from PIL import Image


img = Image.open(r'F:\work\python\clone\2d\Pytorch-UNet\data\imgs\sample\Image_20240622155143140_OUT.png')
print(img)

<PIL.PngImagePlugin.PngImageFile image mode=1 size=3072x2048 at 0x1457B1B0CD0>


In [5]:
import cv2

img1=cv2.imread(r'F:\work\python\clone\2d\Pytorch-UNet\data\imgs\sample\barsample1_OUT.png')
print(img1)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [1]:
import torch
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cuda


In [3]:
import argparse
import logging
import os

import numpy as np
import torch
import torch.nn.functional as F
from PIL import Image
from torchvision import transforms

from utils.data_loading import BasicDataset
from unet import UNet
from utils.utils import plot_img_and_mask

def predict_img(net, full_img, device, scale_factor=1, out_threshold=0.5):
    net.eval()
    img = torch.from_numpy(BasicDataset.preprocess(None, full_img, scale_factor, is_mask=False))
    img = img.unsqueeze(0)
    img = img.to(device=device, dtype=torch.float32)
    logging.info(f'Preprocessed image shape: {img.shape}')

    with torch.no_grad():
        output = net(img).cpu()
        output = F.interpolate(output, (full_img.size[1], full_img.size[0]), mode='bilinear')
        if net.n_classes > 1:
            mask = output.argmax(dim=1)
        else:
            mask = torch.sigmoid(output) > out_threshold
    logging.info(f'Predicted mask unique values: {torch.unique(mask)}')
    return mask[0].long().squeeze().numpy()

def get_args():
    parser = argparse.ArgumentParser(description='Predict mask from input images')
    parser.add_argument('--model', '-m', default='2d/Pytorch-UNet/model/checkpoint_epoch10.pth', metavar='FILE',
                        help='Specify the file in which the model is stored')
    parser.add_argument('--input', '-i', metavar='INPUT', nargs='+', help='Filenames of input images')
    parser.add_argument('--output', '-o', metavar='OUTPUT', nargs='+', help='Filenames of output images')
    parser.add_argument('--viz', '-v', action='store_true',
                        help='Visualize the images as they are processed')
    parser.add_argument('--no-save', '-n', action='store_true', help='Do not save the output mask')
    parser.add_argument('--mask-threshold', '-t', type=float, default=0.5,
                        help='Minimum probability value to consider a mask pixel white')
    parser.add_argument('--scale', '-s', type=float, default=0.5,
                        help='Scale factor for the input images')
    parser.add_argument('--bilinear', action='store_true', default=False, help='Use bilinear upsampling')
    parser.add_argument('--classes', '-c', type=int, default=2, help='Number of classes')

    args = parser.parse_args()

    if args.input is None:
        args.input = [r'F:\work\python\clone\2d\Pytorch-UNet\data\imgs\barsample.jpg']

    return args

def get_output_filenames(args):
    def _generate_name(fn):
        return f'{os.path.splitext(fn)[0]}_OUT.png'
    return args.output or list(map(_generate_name, args.input))

def mask_to_image(mask: np.ndarray, mask_values):
    logging.info(f'Mask shape: {mask.shape}, unique values: {np.unique(mask)}')
    if isinstance(mask_values[0], list):
        out = np.zeros((mask.shape[-2], mask.shape[-1], len(mask_values[0])), dtype=np.uint8)
    elif mask_values == [0, 1]:
        out = np.zeros((mask.shape[-2], mask.shape[-1]), dtype=bool)
    else:
        out = np.zeros((mask.shape[-2], mask.shape[-1]), dtype=np.uint8)

    if mask.ndim == 3:
        mask = np.argmax(mask, axis=0)

    for i, v in enumerate(mask_values):
        out[mask == i] = v

    return Image.fromarray(out)

if __name__ == '__main__':
    args = get_args()

    img_dir = r"F:\work\python\clone\2d\Pytorch-UNet\data\imgs\sample"
    fname = os.listdir(img_dir)
    for name in fname:
        fname2 = os.path.join(img_dir, name)
        if args.input is None:
            args.input = [fname2]
        else:
            args.input.append(fname2)

    logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

    in_files = args.input
    out_files = get_output_filenames(args)

    net = UNet(n_channels=3, n_classes=args.classes, bilinear=args.bilinear)

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    logging.info(f'Loading model {args.model}')
    logging.info(f'Using device {device}')

    net.to(device=device)
    state_dict = torch.load(args.model, map_location=device)
    logging.info(f'Model loaded with parameters: {list(net.parameters())[0].data}')
    mask_values = state_dict.pop('mask_values', [0, 1])
    net.load_state_dict(state_dict)

    logging.info('Model loaded!')

    for i, filename in enumerate(in_files):
        logging.info(f'Predicting image {filename} ...')
        img = Image.open(filename)

        mask = predict_img(net=net,
                           full_img=img,
                           scale_factor=args.scale,
                           out_threshold=args.mask_threshold,
                           device=device)



usage: ipykernel_launcher.py [-h] [--model FILE] [--input INPUT [INPUT ...]]
                             [--output OUTPUT [OUTPUT ...]] [--viz]
                             [--no-save] [--mask-threshold MASK_THRESHOLD]
                             [--scale SCALE] [--bilinear] [--classes CLASSES]
ipykernel_launcher.py: error: unrecognized arguments: -f C:\Users\Liminghui\AppData\Roaming\jupyter\runtime\kernel-b15d4986-7d81-481e-a485-73882b6175e1.json


SystemExit: 2

F:\work\environment\envs\bar\lib\site-packages\IPython\core\interactiveshell.py:3585: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


SyntaxError: invalid syntax. Perhaps you forgot a comma? (951371657.py, line 1)

In [5]:
from PIL import Image
import numpy as np
import os

def get_max_gray_value(image_path):
    # 打开图像
    img = Image.open(image_path).convert('L')  # 转换为灰度图像

    # 转换为numpy数组
    img_array = np.array(img)

    # 获取最高灰度值
    max_gray_value = img_array.max()
    print(f"最高灰度值: {max_gray_value}")

    return img_array, img

def replace_gray_value(img_array, old_value, new_value):
    # 将灰度值为old_value的像素转换为new_value
    img_array[img_array == old_value] = new_value

    # 转换为图像
    new_img = Image.fromarray(img_array)

    return new_img

if __name__ == "__main__":
    # 替换为您的图片路径
    # image_path = 'path_to_your_image.png'
    image_path = r"F:\work\dataset\rebar2D\train2\mask"
    output_dir = r"F:\work\dataset\rebar2D\train2\TEMP"
    for filename in os.listdir(image_path):
        if filename.endswith(".png"):
            input_path = os.path.join(image_path, filename)
            # 获取最高灰度值并返回图像数组
            img_array, img = get_max_gray_value(input_path)

            # 将灰度值为1的像素转换为255
            new_img = replace_gray_value(img_array, 1, 255)

            # 保存新图像
            new_image_path = os.path.join(output_dir, filename)
            new_img.save(new_image_path)
            print(f"新图像已保存到: {new_image_path}")
    # # 获取最高灰度值并返回图像数组
    # img_array, img = get_max_gray_value("/kaggle/input/rebar2d/train2/mask/Image_20240622152006003_mask.png")
    # 
    # # 将灰度值为1的像素转换为255
    # new_img = replace_gray_value(img_array, 1, 255)
    # 
    # # 保存新图像
    # new_image_path = 'path_to_save_new_image.png'
    # new_img.save(new_image_path)
    # print(f"新图像已保存到: {new_image_path}")


最高灰度值: 1
新图像已保存到: F:\work\dataset\rebar2D\train2\TEMP\Image_20240622152006003_mask.png
最高灰度值: 1
新图像已保存到: F:\work\dataset\rebar2D\train2\TEMP\Image_20240622152022155_mask.png
最高灰度值: 1
新图像已保存到: F:\work\dataset\rebar2D\train2\TEMP\Image_20240622152027051_mask.png
最高灰度值: 1
新图像已保存到: F:\work\dataset\rebar2D\train2\TEMP\Image_20240622152032646_mask.png
最高灰度值: 1
新图像已保存到: F:\work\dataset\rebar2D\train2\TEMP\Image_20240622152038023_mask.png
最高灰度值: 1
新图像已保存到: F:\work\dataset\rebar2D\train2\TEMP\Image_20240622152043066_mask.png
最高灰度值: 1
新图像已保存到: F:\work\dataset\rebar2D\train2\TEMP\Image_20240622152049220_mask.png
最高灰度值: 1
新图像已保存到: F:\work\dataset\rebar2D\train2\TEMP\Image_20240622152054365_mask.png
最高灰度值: 1
新图像已保存到: F:\work\dataset\rebar2D\train2\TEMP\Image_20240622152100108_mask.png
最高灰度值: 1
新图像已保存到: F:\work\dataset\rebar2D\train2\TEMP\Image_20240622152105224_mask.png
最高灰度值: 1
新图像已保存到: F:\work\dataset\rebar2D\train2\TEMP\Image_20240622152110857_mask.png
最高灰度值: 1
新图像已保存到: F:\work\dataset\rebar2D\t

In [ ]:
import os
import json
import numpy as np
import cv2
from labelme import utils
from PIL import Image

def labelme_to_yolov8(labelme_dir, output_dir):
    os.makedirs(output_dir, exist_ok=True)
    os.makedirs(os.path.join(output_dir, "images"), exist_ok=True)
    os.makedirs(os.path.join(output_dir, "labels"), exist_ok=True)
    os.makedirs(os.path.join(output_dir, "masks"), exist_ok=True)

    for filename in os.listdir(labelme_dir):
        if filename.endswith(".json"):
            json_path = os.path.join(labelme_dir, filename)
            with open(json_path) as f:
                data = json.load(f)
            
            image_data = utils.img_b64_to_arr(data['imageData'])
            img = Image.fromarray(image_data)
            img.save(os.path.join(output_dir, "images", filename.replace(".json", ".jpg")))

            shapes = data['shapes']
            mask = np.zeros(image_data.shape[:2], dtype=np.uint8)

            for shape in shapes:
                points = np.array(shape['points'], dtype=np.int32)
                cv2.fillPoly(mask, [points], color=1)
            
            mask_img = Image.fromarray(mask * 255)
            mask_img.save(os.path.join(output_dir, "masks", filename.replace(".json", ".png")))

            label_path = os.path.join(output_dir, "labels", filename.replace(".json", ".txt"))
            with open(label_path, 'w') as f:
                f.write(f"{filename.replace('.json', '')} {mask_path.replace('.json', '.png')}\n")

# 使用示例
labelme_dir = "path/to/labelme/json"
output_dir = "path/to/yolov8/dataset"
labelme_to_yolov8(labelme_dir, output_dir)


In [ ]:
import os
import json

def convert_json_to_txt(labelme_dir, output_dir):
    os.makedirs(output_dir, exist_ok=True)
    
    json_files = [f for f in os.listdir(labelme_dir) if f.endswith('.json')]
    
    for filename in json_files:
        json_path = os.path.join(labelme_dir, filename)
        txt_filename = filename.replace('.json', '.txt')
        txt_path = os.path.join(output_dir, txt_filename)
        
        with open(json_path) as f:
            data = json.load(f)
        
        with open(txt_path, 'w') as f:
            for shape in data['shapes']:
                label = shape['label']

                points = shape['points']
                points_str = ' '.join([f"{x},{y}" for x, y in points])
                f.write(f"{label} {points_str}\n")

# 使用示例
labelme_dir = "path/to/labelme/json"
output_dir = "path/to/output/txt"
convert_json_to_txt(labelme_dir, output_dir)


In [2]:
import os  # 导入操作系统接口模块
import json  # 导入JSON处理模块

# 定义一个函数，将Labelme格式的JSON文件转换为TXT文件
def convert_json_to_txt(labelme_dir, output_dir):
    # 创建输出目录，如果目录已存在则忽略
    os.makedirs(output_dir, exist_ok=True)
    
    # 获取指定目录下的所有JSON文件
    json_files = [f for f in os.listdir(labelme_dir) if f.endswith('.json')]
    
    # 遍历每一个JSON文件
    for filename in json_files:
        # 获取JSON文件的完整路径
        json_path = os.path.join(labelme_dir, filename)
        # 生成对应的TXT文件名
        txt_filename = filename.replace('.json', '.txt')
        # 获取TXT文件的完整路径
        txt_path = os.path.join(output_dir, txt_filename)
        
        # 读取JSON文件
        with open(json_path) as f:
            data = json.load(f)
        
        # 使用一个字典来存储每个标签对应的所有坐标点
        label_points = {}
        
        # 遍历JSON文件中的每一个标注
        for shape in data['shapes']:
            # 获取标注的类别标签
            label = shape['label']
            if label == 'rebar':
                label = '0'
            # 获取标注的坐标点
            points = shape['points']
            # 如果该标签尚未在字典中，则初始化一个列表
            if label not in label_points:
                label_points[label] = []
            # 将当前形状的坐标点添加到列表中
            label_points[label].extend(points)
        
        # 打开TXT文件以写入模式
        with open(txt_path, 'w') as f:
            # 遍历字典中的每一个标签
            for label, points in label_points.items():
                # 将所有坐标点格式化为字符串
                points_str = ' '.join([f"{x} {y}" for x, y in points])
                # 写入TXT文件，每行一个标签及其所有坐标点
                f.write(f"{label} {points_str}\n")

# 使用示例
labelme_dir = r"F:\work\python\clone\dataset\rebar2d\labelme_jsons"  # 指定Labelme JSON文件所在目录
output_dir = r"F:\work\python\clone\dataset\rebar2d\yololabel"  # 指定输出的TXT文件目录
convert_json_to_txt(labelme_dir, output_dir)  # 调用函数进行转换


In [ ]:
import os  # 导入操作系统模块
import json  # 导入JSON模块

def convert_json_to_txt_with_normalization_and_mapping(labelme_dir, output_dir, label_mapping):
    os.makedirs(output_dir, exist_ok=True)  # 创建输出目录，如果不存在则创建
    
    json_files = [f for f in os.listdir(labelme_dir) if f.endswith('.json')]  # 获取目录下所有JSON文件的列表
    
    for filename in json_files:  # 遍历每个JSON文件
        json_path = os.path.join(labelme_dir, filename)  # 构建JSON文件的完整路径
        txt_filename = filename.replace('.json', '.txt')  # 构建输出TXT文件的文件名
        txt_path = os.path.join(output_dir, txt_filename)  # 构建输出TXT文件的完整路径
        
        with open(json_path) as f:  # 打开JSON文件
            data = json.load(f)  # 加载JSON数据
        
        image_height = data['imageHeight']  # 获取图像的高度
        image_width = data['imageWidth']  # 获取图像的宽度
        
        with open(txt_path, 'w') as f:  # 打开（或创建）TXT文件以写入模式
            for shape in data['shapes']:  # 遍历每个形状
                label = shape['label']  # 获取形状的标签
                points = shape['points']  # 获取形状的坐标点
                normalized_points = [(x / image_width, y / image_height) for x, y in points]  # 归一化坐标点
                mapped_label = label_mapping.get(label, -1)  # 获取标签的映射值，默认为-1
                
                for x, y in normalized_points:  # 遍历归一化后的坐标点
                    f.write(f"{mapped_label} {x:.6f},{y:.6f}\n")  # 将标签和坐标点写入TXT文件，每行一个点

# 使用示例

labelme_dir = r"F:\work\python\clone\dataset\rebar2d\labelme_jsons"  # 指定Labelme JSON文件所在目录
output_dir = r"F:\work\python\clone\dataset\rebar2d\yololabel"  # 指定输出的TXT文件目录
label_mapping = {  # 标签映射字典
    "rebar": 0
    # 添加更多标签映射
}
convert_json_to_txt_with_normalization_and_mapping(labelme_dir, output_dir, label_mapping)  # 调用函数进行转换


In [3]:
import os  # 导入操作系统模块
import json  # 导入JSON模块

def convert_json_to_txt_with_normalization_and_mapping(labelme_dir, output_dir, label_mapping):
    os.makedirs(output_dir, exist_ok=True)  # 创建输出目录，如果不存在则创建
    
    json_files = [f for f in os.listdir(labelme_dir) if f.endswith('.json')]  # 获取目录下所有JSON文件的列表
    
    for filename in json_files:  # 遍历每个JSON文件
        json_path = os.path.join(labelme_dir, filename)  # 构建JSON文件的完整路径
        txt_filename = filename.replace('.json', '.txt')  # 构建输出TXT文件的文件名
        txt_path = os.path.join(output_dir, txt_filename)  # 构建输出TXT文件的完整路径
        
        with open(json_path) as f:  # 打开JSON文件
            data = json.load(f)  # 加载JSON数据
        
        image_height = data['imageHeight']  # 获取图像的高度
        image_width = data['imageWidth']  # 获取图像的宽度
        
        with open(txt_path, 'w') as f:  # 打开（或创建）TXT文件以写入模式
            for shape in data['shapes']:  # 遍历每个形状
                label = shape['label']  # 获取形状的标签
                points = shape['points']  # 获取形状的坐标点
                normalized_points = [(x / image_width, y / image_height) for x, y in points]  # 归一化坐标点
                mapped_label = label_mapping.get(label, -1)  # 获取标签的映射值，默认为-1
                
                # 将标签和所有归一化后的坐标点写入TXT文件，一行表示一个实例
                points_str = " ".join([f"{x:.6f} {y:.6f}" for x, y in normalized_points])  # 将坐标点转换为字符串
                f.write(f"{mapped_label} {points_str}\n")  # 写入TXT文件

# 使用示例
labelme_dir = r"F:\work\python\clone\dataset\rebar2d\labelme_jsons"  # 指定Labelme JSON文件所在目录
output_dir = r"F:\work\python\clone\dataset\rebar2d\yololabel"  # 指定输出的TXT文件目录
label_mapping = {  # 标签映射字典
    "rebar": 0
    # 添加更多标签映射
}
convert_json_to_txt_with_normalization_and_mapping(labelme_dir, output_dir, label_mapping)  # 调用函数进行转换
